language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jade-frontmatter' ]; then cd .. && eval "mv $currentfolder generator-jade-frontmatter" && cd generator-jade-frontmatter; fi
notifications:
  email: false
